### ISSUE TITLE
ToDo things

### ISSUE THREAD

**Issue by gmonteeeiro** [iptv-player/api#1]
- [ ] Create m3u file reader
   - [x] Echo channels in json format
   - [ ] Group channels by `group-title`
   - [ ] Group channels by `tvg-id`

**Comment by gmonteeeiro** [comment]
- [ ] Fazer download do arquivo através de uma url
- [ ] Deletar arquivo após utilizá-lo
